CHAPTER_LINKS = [
    "https://lu.ru/sortament/kategorii_osveweniya/",
    # "https://lu.ru/sortament/mebel/",
    "https://lu.ru/sortament/rooms/gostinaya/",
    "https://lu.ru/sortament/rooms/spalnya/",
    "https://lu.ru/sortament/rooms/detskaya/",
    "https://lu.ru/sortament/rooms/prihozhaya/",
    "https://lu.ru/sortament/rooms/kabinet/",
    "https://lu.ru/sortament/rooms/kuhnya_stolovaya/",
    "https://lu.ru/sortament/rooms/sanuzel/",
    "https://lu.ru/sortament/rooms/dacha/",
]

CATEGORY_LINKS = [
    "https://lu.ru/sortament/mebel/stulya/",
    "https://lu.ru/sortament/mebel/komplekty/",
    "https://lu.ru/sortament/mebel/krovati/",
    "https://lu.ru/sortament/mebel/veshalki/",
    "https://lu.ru/sortament/mebel/kompyuternye_kresla/",
    "https://lu.ru/sortament/svetilniki/nastennye/",
    "https://lu.ru/sortament/nastolnye_lampy_i_torshery/nastolnye_lampy/",
    "https://lu.ru/sortament/mebel/stoly/",
    "https://lu.ru/sortament/mebel/beskarkasnaya_mebel/",
    "https://lu.ru/sortament/mebel/bufety/",
    "https://lu.ru/sortament/mebel/stellazhi/",
    "https://lu.ru/sortament/mebel/zerkala/",
    "https://lu.ru/sortament/tovary_dlya_doma/",
    "https://lu.ru/sortament/posuda/",
    "https://lu.ru/sortament/posuda/posuda_dlya_prigotovleniya/",
    "https://lu.ru/sortament/posuda/posuda_dlya_prigotovleniya/nozhi/",
    "https://lu.ru/sortament/posuda/posuda_dlya_servirovki/stolovaya_posuda/",
    "https://lu.ru/sortament/posuda/prisposobleniya_dlya_hraneniya/",
    "https://lu.ru/sortament/posuda/posuda_dlya_prigotovleniya/prisposobleniya_dlya_zatochki_lezvij/",
    "https://lu.ru/sortament/posuda/posuda_dlya_servirovki/nabory_posudy_dlya_servirovki_stola/",
    "https://lu.ru/sortament/posuda/posuda_dlya_servirovki/stolovye_pribory/",
    "https://lu.ru/sortament/tehnika_dlya_kuhni/",
    "https://lu.ru/sortament/aksessuary/girlyandy/",
    "https://lu.ru/sortament/aksessuary/lampochki/",
    "https://lu.ru/sortament/aksessuary/fonari/",
    "https://lu.ru/sortament/elektro/",
    "https://lu.ru/sortament/aksessuary/dyuralajt/",
    "https://lu.ru/sortament/bra_i_podsvetka_dlya_kartin/zerkala/",
    "https://lu.ru/sortament/aksessuary/komplektuyuwie/",
    "https://lu.ru/sortament/aksessuary/novogodnee_osvewenie/",
    "https://lu.ru/sortament/klimat_tehnika/ventilyatory/",
]